### ISSUE TITLE
Database storage directory

### ISSUE THREAD

**Issue by pixelmachine** [sjelfull/craft-countryredirect#12]
Currently the MaxMind database is written to a directory within the `craft-countryredirect/src/` directory of the plugin. On our server the vendor folder is only writable by Composer NOT Craft, this causes the plugin to stop working each time it's updated as the directory does not exist and cannot be created.

It seems that it would make more sense to download the database to the `storage/` directory which must always writable by Craft. This could be optional I suppose.

Thanks @sjelfull

**Comment by sjelfull** [comment]
Totally make sense to both use `storage` and to make this configurable. It's been on a todo list for a while - i'll get to it asap.

**Comment by sjelfull** [comment]
This will be out soon, in the next big update.
