### ISSUE TITLE
Database Download Problems

### ISSUE THREAD

**Issue by masonry47** [sjelfull/craft-countryredirect#22]
Hi there! 

We have begun to receive an error when trying to manually download the database by hitting the URL or clicking the button in the settings. The Craft log says this.

"Was not able to get checksum from GeoLite url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.md5"

We are assuming that it is related to this.

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

1. Go to Country Redirect Settings
2. Click on "Download Database"
3. At that point we receive this

<img width="379" alt="Screen Shot 2020-01-04 at 8 10 22 AM" src="https://user-images.githubusercontent.com/48130527/71766812-bcdb1500-2ec9-11ea-9a3a-8561f473acc6.png">

- Craft version: 3.3.19
- Country Redirect Version: 2.0.13

Thank you!

**Comment by sjelfull** [comment]
Thanks for reporting, will release a fix next week.

**Comment by sjelfull** [comment]
Just a quick update: The rewrite is taking longer than planned, but working on getting it out asap.

In the mean time, its possible to download the database manually and place it in the database folder if needed.

**Comment by lukepearce** [comment]
Hey, is this still a problem? I can't seem to download the database manually either using the URL http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz .. server is offline?

**Comment by masonry47** [comment]
Hey @sjelfull 

Just checking on the status of this, to see if there will be an updated version soon.  Thanks so much!

**Comment by brettburwell** [comment]
Hi @sjelfull. Checking in on the status of this update. 

We've bumped into the same issue. Currently the redirect functionality appears to be broken entirely (or at least not working as expected). 

Per your recommendation I tried manually replacing the database by dropping a copy into the following location: 
`/vendor/superbig/craft-countryredirect/src/database/GeoLite2-Country.mmdb.gz`

Is that correct? Or does it need to be named something else or uploaded to a different location? 

Any guidance or updates would be much appreciated. Thanks!

**Comment by sjelfull** [comment]
Sorry about the long wait on this (life has been a bit crazy). I just tagged v2.1.0 which should fix this.

Note that you have to go to MaxMind.com and get a free license key, and then add it to the plugin config either through the plugin settings or a config file.

![image](https://user-images.githubusercontent.com/10508/83327747-7625f700-a27e-11ea-9d1c-4588a5478786.png)

Then you should be able to update the database as normally.

Let me know if you have any troubles!

**Comment by brettburwell** [comment]
Good to hear from you @sjelfull. Thanks for the response and update.

I'm following along on #25 and am happy to know this one's moving forward. 

I hope you've been hanging in there during these highly unusual times.
