### ISSUE TITLE
Support alias in site Base URLs

### ISSUE THREAD

**Issue by zizther** [sjelfull/craft-countryredirect#26]
**Describe the bug**
I am using aliases for all Base URLs for all locales the site needs to support.

I am outputting the locale nav using `craft.countryRedirect.getLinks()`, it does not seem to output the alias in `{{ link.getLink({ title: titles[link.getId()] }) }}`.

Do you think it would be possible to support alias's so that the Base URL does not need to be hardcoded in this field?

**Additional context**
- Country Redirect 2.1.1
- Craft version: 3.5.10.1

**Comment by sjelfull** [comment]
Thanks, will add this in an upcoming release!

**Comment by zizther** [comment]
Is it likely this feature will be added soon?
