### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by eheiser** [sjelfull/craft-countryredirect#33]
![screenshot_01](https://user-images.githubusercontent.com/86934/137777164-c2e53fee-7946-4620-b086-61b961e187f2.png)

Trying to redirect US & Canada visitors to a /global/usa-canada, my settings are OK I think but I keep running into the error you see in the screenshot. Any suggestions? Any possibility of getting on a google meet to doublecheck my settings?

**Comment by sjelfull** [comment]
Thanks for reporting, fixed in 2.2.0
