### ISSUE TITLE
2.0.10 Causing site errors with Craft 3.1.7

### ISSUE THREAD

**Issue by matthewmrotter** [sjelfull/craft-countryredirect#9]
Going to the secondary language on a site throws us an error, only when we go directly to the url not using a site redirect button. The error logs give us:

Error: Class 'superbig\countryredirect\services\App' not found in /home/234685.cloudwaysapps.com/genxabcuuj/public_html/vendor/superbig/craft-countryredirect/src/services/CountryRedirectService.php:418

**Comment by sjelfull** [comment]
Thanks for reporting, will cut a release soon that fixes this.

**Comment by sjelfull** [comment]
Tagged a release now, which should be available soon. Let me know if that fixes the problem.
